export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SEARCH_CLIENT = "SEARCH_CLIENTS";
export const FIRST_CAHT_SUCCESS = "FIRST_CAHT_SUCCESS";
export const FIRST_CHAT_FAIL = "FIRST_CAHT_FAIl";

export const CHAT_SUCCESS = "CHAT_SUCCESS";
export const CHAT_FAIL = "CHAT_FAIL";
export const GET_CHAT_DATA_SUCCESS = "GET_CHAT_DATA_SUCCESS";
export const GET_CHAT_DATA_FAIL = "GET_CHAT_DATA_FAIL";

export const GET_GROUP_CHAT_SUCCESS = "GET_GROUP_CHAT_SUCCESS";
export const GET_GROUP_CHAT_FAIL = "GET_GROUP_CHAT_FAIL";

export const GROUP_CREATE_SUCCESS = "GROUP_CREATE_SUCCESS";
export const GROUP_CREATE_FAIL = "GROUP_CREATE_FAIL";

export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_FAIL = "GET_GROUPS_FAIL";

export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAIL = "CREATE_GROUP_FAIL";

export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAIL = "GET_NOTIFICATIONS_FAIL";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const GET_LOCATION = "GET_LOCATION";

export const GET_PUZZLE_DATA_SUCCESS="GET_PUZZLE_DATA_SUCCESS";
export const GET_PUZZLE_DATA_FAIL="GET_PUZZLE_DATA_FAIL";
export const SET_SOCRE="SET_SCORE";

export const PUZZLE_FINISHED="PUZZLE_FINISHED";

export const SEND_LOCATION_SUCCESS="SEND_LOCATION_SUCCESS";

export const CHANGE_SETTING_SUCCESS="CHANGE_SETTING_SUCCESS";

export const CHNAGE_SEND_STATUS="CHNAGE_SEND_STATUS";

export const MARK_AS_READ_CHAT="MARK_AS_READ_CHAT";

export const GET_SCORE_SUCCESS="GET_SCORE_SUCCESS";
export const GET_SCORE_START="GET_SCORE_START";

export const GET_NEAR_BY_USERS_SUCCESS="GET_NEAR_BY_USERS_SUCCESS"
;
export const GET_NEAR_BY_USERS_STRAT="GET_NEAR_BY_USERS";

export const BASE_URL="https://www.tekhalini.com/";